// todolist-react/src/component/login/LoginPage.tsx
import React, { useState } from 'react';
import { makeStyles } from '@material-ui/core/styles';
import Button from '@material-ui/core/Button';
import TextField from '@material-ui/core/TextField';
import Card from '@material-ui/core/Card';
import CardActions from '@material-ui/core/CardActions';
import CardContent from '@material-ui/core/CardContent';
import CircularProgress from '@material-ui/core/CircularProgress';
import Typography from '@material-ui/core/Typography';
import CardMedia from '@material-ui/core/CardMedia';

import { useAuthentification, AuthentificationState } from '../../context/AuthentificationContext';

const useStyles = makeStyles({
  cardContainer: {
    padding: 20,
    textAlign: 'center'
  },
  card: {
    display: 'inline-block',
    maxWidth: 345
  },
  hint: {
    fontSize: 12
  },
  media: {
    height: 140
  }
});

type Props = {
  redirect?: string;
};

export default function LoginPage(props: Props) {
  const classes = useStyles();
  const { state, login } = useAuthentification();
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');

  const canLogin = state === AuthentificationState.NonAuthentificated && username && password;
  const onGoingLogin = state === AuthentificationState.OnGoingAuthentification;
  return (
    <div className={classes.cardContainer}>
      <Card className={classes.card}>
        <CardMedia
          className={classes.media}
          image="https://upload.wikimedia.org/wikipedia/commons/f/f6/Eiffel_Tower_and_the_Trocadero%2C_Exposition_Universal%2C_1900%2C_Paris%2C_France.jpg"
          title="Eiffel Tower"
        />
        <CardContent>
          <Typography gutterBottom variant="h5" component="h2">
            Welcome to TodoList React
          </Typography>
          <Typography className={classes.hint} color="textSecondary" gutterBottom>
            Try with password: “password”
          </Typography>
          <TextField label="Username" value={username} onChange={p => setUsername(p.currentTarget.value)} />
          <br />
          <TextField
            label="Password"
            type="password"
            value={password}
            onChange={p => setPassword(p.currentTarget.value)}
          />
        </CardContent>
        <CardActions>
          <Button color="primary" disabled={!canLogin} onClick={() => login(username, password)}>
            Login
          </Button>
          {onGoingLogin ? <CircularProgress size={24} /> : <></>}
        </CardActions>
      </Card>
    </div>
  );
}

// todolist-vue/src/components/LoginPage.vue
<template>
  <div id="login-page">
    <md-card id="login-card">
      <md-card-media>
        <img
          src="https://upload.wikimedia.org/wikipedia/commons/f/f6/Eiffel_Tower_and_the_Trocadero%2C_Exposition_Universal%2C_1900%2C_Paris%2C_France.jpg"
          alt="Eiffel Tower"
        />
      </md-card-media>

      <md-card-header>
        <div class="md-title">Welcome to TodoList Vue</div>
        <div class="md-subhead">Try with password: “password”</div>
      </md-card-header>

      <md-card-content>
        <md-field>
          <label>Username</label>
          <md-input v-model="username"></md-input>
        </md-field>
        <md-field>
          <label>Password</label>
          <md-input v-model="password"></md-input>
        </md-field>
      </md-card-content>

      <md-card-actions>
        <md-button>Login</md-button>
      </md-card-actions>
    </md-card>
  </div>
</template>

<script>
import Vue from "vue";
import { MdButton, MdCard, MdField } from "vue-material/dist/components";

Vue.use(MdButton);
Vue.use(MdCard);
Vue.use(MdField);

export default {
  name: "LoginPage",
  props: { redirect: String },
  data: () => ({ username: "", password: "" })
};
</script>

<style scoped>
#login-page {
  text-align: center;
}
#login-card {
  max-width: 320px;
  display: inline-block;
}
</style>
